services:
  backend:
    image: testing-backend-image:latest
    container_name: testing-backend-container
    networks:
      - my_bridge_net
    expose:
      - "8001"    
    command: gunicorn --bind 0.0.0.0:8001 testing.wsgi:application
    # 2. Прокидываем внешнюю папку с базой данных      
    volumes:
      - /home/ubuntu12/sqlite_data:/app_testing/db_folder
      - /home/ubuntu12/app_testing/static_root:/app_testing/staticfiles  # Хост : Контейнер
      
    # 3. Добавляем автоматический перезапуск
    restart: always

networks:
  my_bridge_net:
    external: true




#     command: "python manage.py runserver 0.0.0.0:8001"

# networks: # создаем сеть
#   my_bridge_net:  # название сети
#     external: true 
